export const GET_ALL_FLIGHTS = 'GET_ALL_FLIGHTS'
export const SORT_FLIGHTS = 'SORT_FLIGHTS'
export const SET_TRANSFER_FILTER_ONE_TRANSFER = 'SET_TRANSFER_FILTER_ONE_TRANSFER'
export const SET_TRANSFER_FILTER_WITHOUT_TRANSFER = 'SET_TRANSFER_FILTER_WITHOUT_TRANSFER'
export const SET_MIN_COST = 'SET_MIN_COST'
export const SET_MAX_COST = 'SET_MAX_COST'
export const CARRIER_LOT_FILTER = 'CARRIER_LOT_FILTER'
export const CARRIER_AEROFLOT_FILTER = 'CARRIER_AEROFLOT_FILTER'



